### ISSUE TITLE
ETHTaipei Hackathon - Infrastructure

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#119]
We need to provide a ready-to-use infrastructure for hackers. We are NOT going to share with hackers emails or access to backend infrastructure. We are going to make a special feature to make them coordinators after authentication. We are going to oversee what's going on inside the backend and provide the support. Also, after finalization, they should be able to download all the artifacts from their ceremony.

__TODOs__
- [x] Custom "special" function to make hackers coordinators as needed #118 
- [x] Decide an EF-billing (or refundable) account for GCP Firebase and AWS S3
- [x] Share access w/ mentors @gurrpi 
- [x] Setup a ceremony for demonstration and gather contributions #117

**Comment by baumstern** [comment]
See also
- [ ]  #124
- [x] #125
