### ISSUE TITLE
Set up  ceremony non interactively

### ISSUE THREAD

**Issue by baumstern** [privacy-scaling-explorations/groth-p0tion#12]
- [ ] modify setup command to take arguments from config file instead of CLI prompt

**Comment by daodesigner** [comment]
Look at contribution test, to set up ceremony noninteractively

**Comment by ctrlc03** [comment]
My bad, I should have directed to the setup tests instead:

https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/test/e2e/01-setup.test.ts#L118

Here are almost all steps required, aside from zkey generation/verification

**Comment by 0xjei** [comment]
> My bad, I should have directed to the setup tests instead:
> 
> Local path generation: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/test/e2e/01-setup.test.ts#L55-L75
> 
> Bucket creation, Upload and setup: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/test/e2e/01-setup.test.ts#L118
> 
> Here are almost all steps required, aside from zkey generation/verification, pot estimation and download:
> 
> what you will need is:
> 
> * extract metadata from r1cs: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/src/helpers/utils.ts#L94
> * calculate min PoT required: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/src/helpers/utils.ts#L37
> * download PoT if not already provided
> * compute first Zkey if not already provided
> * follow steps in the test above

Great!

Here I would leave the option of downloading minimal PTAU (if not provided a-priori) and generating a new zKey with PTAU + R1CS (if not provided a-priori). On the other hand, if provided a-priori, the zKey should be verified to validate the zKey + PTAU + R1CS triplet and avoid an incorrect ceremony being set.

@ctrlc03

**Comment by ctrlc03** [comment]
> > My bad, I should have directed to the setup tests instead:
> > Local path generation: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/test/e2e/01-setup.test.ts#L55-L75
> > Bucket creation, Upload and setup: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/test/e2e/01-setup.test.ts#L118
> > Here are almost all steps required, aside from zkey generation/verification, pot estimation and download:
> > what you will need is:
> > 
> > * extract metadata from r1cs: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/src/helpers/utils.ts#L94
> > * calculate min PoT required: https://github.com/quadratic-funding/mpc-phase2-suite/blob/dev/packages/actions/src/helpers/utils.ts#L37
> > * download PoT if not already provided
> > * compute first Zkey if not already provided
> > * follow steps in the test above
> 
> Great!
> 
> Here I would leave the option of downloading minimal PTAU (if not provided a-priori) and generating a new zKey with PTAU + R1CS (if not provided a-priori). On the other hand, if provided a-priori, the zKey should be verified to validate the zKey + PTAU + R1CS triplet and avoid an incorrect ceremony being set.
> 
> @ctrlc03

Yup exactly
