### ISSUE TITLE
Finalize: verify correctness of finalization

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#13]
__Pre-conditions__

- [x] #45 
- [x] #44 

__Blocked__
- See steps below

**Comment by 0xjei** [comment]
__Assumption__

We only have valid circuits.

_Pre-condition_

- The ceremony has been finalized.
- The script must run on a local machine (no server/cloud).

- Weak check => Ceremony status = FINALIZED
- Mid/Strong check => Weak check & final contribution docs exists & artifacts exist and are linked in the contribution docs.

__Goal__

- [ ] Create a custom script to validate the finalization of the ceremony
- [ ] Bonus: the script could be an interactive or non-interactive CLI command (`p0tion verify:finalize --ceremony <name>` in order to discriminate w/ `verify:setup`).

_Scope creep bonus_

From sprint planning discussions.

- [ ] Bonus x2: Generalize for other trusted setup ceremonies (not our infra).
- [ ] Bonus x3: write in Rust

__Steps__

- [ ] Select/Provide ceremony identifier.

Per each circuit
- [ ] Download Final zKey and Final - 1 zKey
- [ ] Download Verification Transcript for Final zKey and Final - 1 zKey
- [ ] Retrieve public finalization beacon
   - [ ] Compute Final zKey from scratch
   - [ ] Match hashes w/ downloaded zKey
   - [ ] Compute verification for the Final zKey
   - [ ] Match Verification transcripts hashes (must be the same in this case - beacon do not change)
- [ ] Download vKey and Verifier contract
   - [ ] Extract from computed one
   - [ ] Match hashes w/ Downloaded
- [ ] Use artifacts to generate a proof
   - [ ] Verify proof w/ vKey
   - [ ] Verify proof w/ Verifier contract

@daodesigner I have summarized the steps based on latest discussions during yesterday Sprint Planning. Lmk if this sounds good and I'll proceed to update the single steps below and open related issues.

**Comment by daodesigner** [comment]
Lgtm! Great job breaking this down 🙂

**Comment by gurrpi** [comment]
IMO, it can be seen as a validation of the functionality of circom and snarkjs. It would be nice to have a description of what the feature is used for from a user perspective:
* In what cases would a user want to do this? 
* What do you expect users to get out of this?
* (If exists) What is the limitation that this feature doesn't guarantee?
  * I am curious if it can tell user that when if every participants of ceremony are compromised, the finalized .zkey is not safe to use.

I think it will eventually described in a document.

**Comment by 0xjei** [comment]
> @0xjei IMO, it can be seen as a validation of the functionality of circom and snarkjs. It would be nice to have a description of what the feature is used for from a user perspective:
> 
> * In what cases would a user want to do this?
> * What do you expect users to get out of this?
> * (If exists) What is the limitation that this feature doesn't guarantee?
>   
>   * I am curious if it can tell user that when if every participants of ceremony are compromised, the finalized .zkey is not safe to use.
> 
> I think it will eventually described in a document.

> IMO, it can be seen as a validation of the functionality of circom and snarkjs

I think you can see this as "trust assumption" made by someone when using p0tion for their Trusted Setup Phase 2 Ceremonies. Obviously, p0tion leverages snarkjs under the hood, so everything we verify here is about two main things: process (operator deployed the infra correctly, coordinator did setup and finalization correctly and so on) and snarkjs too.

> It would be nice to have a description of what the feature is used for from a user perspective

Let's try to discriminate by user type (coordinator and participant). IMHO coordinator could have interest to double-check the ceremony finalization from operator-side (if their did a great job setting up things or not) and snarkjs/p0tion software (command) side.

> In what cases would a user want to do this?

A participant or external user may have interest to run this script locally on their own machine to be sure. Not everyone, but someone could definitely have interest. Why? Similar to coordinator, they would probably want to check the operator/infra-side, snarkjs/p0tion software (command) and coordinator work (running commands).

> What do you expect users to get out of all this?

This verification script is important to make the user 99.99% sure that everything above worked as expected and that no-one has tampered with or altered information about the artifacts. For example, if the coordinator/operator/hacker modify the last zKey with one invalid after running successfully the `finalize` command, nobody will notice until someone runs this verification command (the re-compute of the final zKey will result in a different zKey from the one in the bucket, leading to inconsistency and errors). In this case, the script will warn the user about a potential tampering of the ceremony. Otherwise, they expect to be sure they could create proofs and verify others without the fear of using something not safe.

> (If any) What is the limitation that this feature does not guarantee?

Currently, we cannot guarantee validity at source level. The circuits could be invalid or work improperly. We are putting a trust here on circuits correctness.

> I am curious if it is able to tell the user that when all participants in the ceremony are compromised, the final .zkey is not safe to use.

Here we are just assuring the correctness related to the finalization of the ceremony. The single contribution verification check done by the backend (in cloud functions) should be tested using another script. The same for the ceremony setup process.

Please let me know if I have answered all your questions or if you have more @gurrpi. Thanks!

**Comment by gurrpi** [comment]
@0xjei Thanks for the quick answers!

> Compute Final zKey from scratch (blocked https://github.com/privacy-scaling-explorations/groth-p0tion/issues/37)

I thought 'from scratch' here meant generating it from circuit and re-doing all contributions.

> For example, if the coordinator/operator/hacker modify the last zKey with one invalid after running successfully the finalize command, nobody will notice until someone runs this verification command (the re-compute of the final zKey will result in a different zKey from the one in the bucket, leading to inconsistency and errors). In this case, the script will warn the user about a potential tampering of the ceremony.

I think this is the main point of this feature and maybe we should strongly recommend users to validate finalized artifacts before using them in production.

**Comment by 0xjei** [comment]
> @0xjei Thanks for the quick answers!
> 
> > Compute Final zKey from scratch (blocked #37)
> 
> I thought 'from scratch' here meant generating it from circuit and re-doing all contributions.

Oops, sorry for the confusion. By "from scratch" I mean to generate the final zKey from scratch starting from the contribution with index "final - 1". This does not include previous generations of contributions. Let me update the issue accordingly to avoid further confusion there.

> > For example, if the coordinator/operator/hacker modify the last zKey with one invalid after running successfully the finalize command, nobody will notice until someone runs this verification command (the re-compute of the final zKey will result in a different zKey from the one in the bucket, leading to inconsistency and errors). In this case, the script will warn the user about a potential tampering of the ceremony.
> 
> I think this is the main point of this feature and maybe we should strongly recommend users to validate finalized artifacts before using them in production.

Absolutly, I agree. We should take care to write this on the documentation too.
