### ISSUE TITLE
Scope out: API that returns ceremony artifact and use that to verify ceremony

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/groth-p0tion#2]
data and artifacts needed to verify the ceremony

**Comment by 0xjei** [comment]
Goal: Seek to comply with the inclusion of a variety of data and artifacts of the ceremony to ensure possible "a posteriori" verification of it.

**Comment by 0xjei** [comment]
### Data
- [ ] External link to circuit template source + commit hash
- [ ] Circuit compiler: version + commit hash
- [ ] Verification software: version + commit hash
- [ ] Contribution:
   - [ ] Contribution signature (checksum or G1/G2 points for Tau^1)
   - [ ] Previous contribution signature
   - [ ] Contributor ID

### Artifacts
- [ ] Link to contributions (zKey) + hash
- [ ] Link to R1CS + hash
- [ ] Link to Phase 1 artifacts (PoT) + hash + source
- [ ] Link to transcript + hash
- [ ] Ceremony Output
   - [ ] Link to final contribution (zKey) + hash
   - [ ] Link to verifier contract + hash 
   - [ ] Link to verification keys + hash

Any information missing to verify the ceremony?

**Comment by daodesigner** [comment]
depends on refactoring
