### ISSUE TITLE
Cannot read medium/large R1CS files

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/groth-p0tion#28]
https://github.com/quadratic-funding/mpc-phase2-suite/issues/164

Prompt user for metadata

Circuit meta data:

**Comment by daodesigner** [comment]
https://github.com/weijiekoh/circom-helper/commit/ed03810a915a3f368150c1f5199af6f9019bb25a

**Comment by 0xjei** [comment]
May I work on it? @daodesigner @gurrpi  

My idea

- [ ] Study the KWJ implementation linked above (I already took a first look at it).
   - [ ] Test it and verify that it works with the latest versions of R1CS produced by Circom. 

Green lights

- [ ] Implement a helper method on `actions/` that takes all metadata (not just constraints)
- [ ] Update the workflow of `setup` command.

Red lights

- [ ] Prompt for circuit constraint size.
- [ ] Derive smallest powers of tau leaving out other metadata (which were only x visuals)
- [ ] Update workflow of `setup` command and collection information

I think SP 5 is okay for these steps above, lmk
