### ISSUE TITLE
Refactoring: Contribute command / cloud functions

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/groth-p0tion#3]

**Comment by 0xjei** [comment]
Updates after 1w of the sprint:

Contribute main (~70% completed) - cloud functions (~25%)

Completed
- Improve entropy prompt for the user.
- Handle scenario when the contributor has already contributed to all circuits of the ceremony.
- Handle timeout scenario (real-time + re-run message).
- Update Cloud Functions related to timeout and progress to the next circuit for contribution.
- Bug fix: next participant on the waiting queue did not automatically start the contribution after the current contributor timeout.
- Listener optimization (current participant (20%), current contributor + circuit (100%))
- Remove duplicated code.
- Handle available space requirement for contribution.
- Improved cloud functions grouping and naming.
- Missing spinner when computing hash.
