### ISSUE TITLE
Doubling the maximum memory limit for Cloud Functions

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#56]
Avoid the error ``Function cannot be initialized. Error: memory limit exceeded.`` subsequent to the last packages update which will not allow Firebase to maintain the default memory limit.

__Note__

- Super low cost impact.
- Should not be done for `verifycontribution` (as it is already configured for 16GiB).
- Functions do not use maximum memory-theoretically they could use it, but from early tests they do not as well as they did not in the past.

**Comment by ctrlc03** [comment]
This is included in https://github.com/quadratic-funding/mpc-phase2-suite/pull/348
