### ISSUE TITLE
Define the verification strategy for ceremony setup

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#58]

**Comment by 0xjei** [comment]
__Goal__

Create a custom script to validate the ceremony configuration. The assumption is that we only have valid circuits (we are not going to check if the circuit is doing the right thing).

__Preconditions__

- The ceremony setup has been completed.
- Check bucket and collection documents.
- The script should run on a local machine (no servers/cloud).
- Checks of a document's information cannot reproduce the input of the setup (e.g., I cannot be sure of a value in the description field being random) but must check that, for example, the end date of a ceremony is greater than the start date, that the prefix was generated from the UID, naming conventions respected between artifacts in the bucket and in the collection, and so on. These checks are going to be indicated as 'Collection Data Checks' below.

__Steps__

Given the ceremony identifier:
- [ ] Verify the ceremony bucket.
   - [ ] Check that the paths names are correct.
       - [ ] Download Powers of Tau file and for each file:
           - [ ] Hash calculation
           - [ ] Comparing the hash with the source (Hermez PPoT ceremony).
           - [ ] Download the R1CS file 
   - [ ] For each circuit.
       - [ ] Download genesis zKey
       - [ ] Verify Genesis zKey using R1CS and PoT.
- [ ] Verify Firestore collections.
   - [ ] Ceremony document.
       - [ ] Path
       - [ ] Collection Data Checks
   - [ ] Ceremony document subcollection (circuits)
       - [ ] Path
       - [ ] Collection Data Checks

**Comment by ctrlc03** [comment]
Great breakdown
