### ISSUE TITLE
Define the verification strategy when ceremony close

### ISSUE THREAD

**Issue by 0xjei** [privacy-scaling-explorations/groth-p0tion#60]

**Comment by 0xjei** [comment]
__Goal__

Create a custom script to validate the ceremony after having received all the contributions from participants. The assumption is that we only have valid circuits (we are not going to check if the circuit is doing the right thing).

__Preconditions__

- The ceremony is now closed and contributions has been successfully registered.
- The script should run on a local machine (no servers/cloud).
- Use the same verification software (version and commit hash).
- We are going to implement a "light" verification. 
   - Since each contribution has multiple point sections that are computed and multiplied with a secret (toxic waste) to generate by hashing the result a contribution signature. Each subsequent contribution "embeds" the signature of the previous one forming a chain. 
   - For this, we will rely on just recalculating the hashes by cross-checking with the data in the verification transcript and then performing verification only for the last contribution, which will allow us to detect whether indeed something went wrong in the previous contributions. This will allow us to verify the chain of contributions but not verify each individual contribution.  

__Steps__

Given the ceremony identifier:
- [ ] Get all ceremony contribution documents
- [ ] For each contribution document:
    - [ ] Check verification software
    - [ ] Get transcript and zKey storage path
    - [ ] Download transcript and zKey
    - [ ] Check and store zKey index
    - [ ] Compute and check zKey hash (stored in the collection)
    - [ ] Compute and check transcript hash (stored in the collection)
    - [ ] Store contributor unique handle, zKey Index and contribution hash (array item)
    - [ ] Parse transcript to check
        - [ ] contribution hash
        - [ ] "zKey ok" should be present (light validity check)
        - [ ] Previous contributions hash (using array items, if any).
    - [ ] Verify (last contribution only)
        - [ ] Compute verification of the contribution
        - [ ] Compute hash of the newly generated transcript and match info (as above)

**Comment by ctrlc03** [comment]
Looks good
