### ISSUE TITLE
security audit

### ISSUE THREAD

**Issue by daodesigner** [privacy-scaling-explorations/groth-p0tion#9]
Scope out Security Audit

**Comment by ctrlc03** [comment]
Components:

- [ ]  actions 
- [ ]  backend (cloud functions)
- [ ]  phase2cli 

Code functionality: 

- [ ] Authentication 
- [ ] Setup 
- [ ] Contribution
- [ ] Finalization 

Steps:

- [ ] Review each functionality on its own
- [ ] Review all together
- [ ] Conduct main test scenarios 
- [ ] Write scenarios as code
- [ ] Report (6 story points including report review and changes)
